// ignore_for_file: unnecessary_const

import 'package:flutter/material.dart';

import './models/category.dart';
import './models/meal.dart';

const DUMMY_CATEGORIES = const [
  Category(
    id: 'c1',
    title: 'Afrikaner',
    color: Colors.purple,
  ),
  Category(
    id: 'c2',
    title: 'Cape Malay',
    color: Colors.red,
  ),
  Category(
    id: 'c3',
    title: 'Indian',
    color: Colors.orange,
  ),
  Category(
    id: 'c4',
    title: 'Venda',
    color: Colors.amber,
  ),
  Category(
    id: 'c5',
    title: 'Xhosa',
    color: Colors.blue,
  ),
  Category(
    id: 'c6',
    title: 'Zulu',
    color: Colors.green,
  ),
  Category(
    id: 'c7',
    title: 'Desert',
    color: Colors.lightBlue,
  ),
  Category(
    id: 'c8',
    title: 'Dried',
    color: Colors.lightGreen,
  ),
  // Category(
  //   id: 'c9',
  //   title: 'French',
  //   color: Colors.pink,
  // ),
  // Category(
  //   id: 'c10',
  //   title: 'Summer',
  //   color: Colors.teal,
  // ),
];

const DUMMY_MEALS = const [
  Meal(
    id: 'm1',
    categories: [
      'c1',
      'c7',
    ],
    title: ' Koeksisters (Plaited Doughnut)',
    affordability: Affordability.Affordable,
    complexity: Complexity.Simple,
    imageUrl:
        'https://www.lacademie.com/wp-content/uploads/2022/01/plaited-doughnut.jpg',
    duration: 150,
    ingredients: [
      'Spicey Syrup',
      '',
      '2 cups granulated sugar',
      '1/4 teaspoon cream of tartar',
      '1 tablespoon chopped Fresh ginger',
      'Fresh squeeze lemon juice ',
      '1 cinnamon stick',
      '1 cup water',
      '',
      'Dough',
      '',
      '1 cup corn flour (100grams)',
      '1 1/2 cups all purpose flour',
      '1/2 teaspoons baking powder',
      '3/4 teaspoon salt',
      '2 tablespoons sugar',
      '1/2 cup milk',
      '1 large egg',
      '25 grams butter melted',
      'oil for deep frying'
    ],
    steps: [
      'In a medium saucepan. Add, cream of tartar, salt, sugar, ginger, lemon juice and cinnamon stick. Bring water to a boil and let it simmer for about 10 minutes, Stirring syrup occasionally. Let it cool and refrigerate until ready to use.',
      'In a large bowl combine all the dry ingredients- corn meal, flour, sugar, baking powder',
      'Then all the wet ingredients milk and egg followed by butter. Knead several times until all the ingredients have been incorporated. Let it rest for about 30 minutes.',
      'Place dough on board and roll out into about 1 inch thickness. Using a cookie cutter or knife cut into strips thin strips and then shorter strips.',
      'Divide the dough into three strands and stretch them out carefully until they are of an even thickness all the way down. Pinch the ends together',
      'Take the left strand and cross it over the middle strand Take the right strand and cross it over the middle strand. Tightly pinch to seal the end.',
      'In a large, sauce pan pour vegetable oil into a pot, until it is at least 3 inches Test to make sure the oil is hot enough by putting a ‘drop’ of batter into the oil. If it is not hot enough, the batter will stay at the bottom of the pot rather than rising to the top. If using a deep fryer, fry at 350 degrees',
      'Gently place koeksisters in the pan',
      'Fry for a few minutes until the bottom side is golden brown.',
      'Turn the over and fry for a few more minutes until the other side is golden brown.',
      'Use a large spoon or something like that to take it out of the oil and directly place in syrup.',
      'Leave to soak in the syrup for a while. Transfer to a cooling rack. Cool completely before eating.',
    ],
    isGlutenFree: false,
    isVegan: false,
    isVegetarian: true,
    isLactoseFree: false,
  ),
  Meal(
    id: 'm2',
    categories: [
      'c1',
      'c7',
    ],
    title: 'Melktert (Milk Tart)',
    affordability: Affordability.Affordable,
    complexity: Complexity.Simple,
    imageUrl:
        'https://www.lacademie.com/wp-content/uploads/2022/01/milk-tart.jpg',
    duration: 35,
    ingredients: [
      'Pastry Crust',
      '',
      '1 1/2 cups (188 grams) all-purpose flour',
      '1/3 cup (35grams ) confectioners sugar powdered sugar',
      '¼ teaspoon salt',
      '9 Tablespoons (125grams) unsalted butter(cold or frozen) , cut into small pieces',
      '1 large egg yolk',
      '',
      'Milk filling',
      '',
      '2 1/4 ( 496 ml) cups milk',
      '2 tablespoon (28grams) butter',
      '2 tablespoons (20 grams) flour',
      '3-4 tablespoons (23- 30grams) cornstarch',
      '1/2 cup (100grams) sugar',
      '2 Large eggs',
      '2 teaspoons vanilla extract',
      '½ teaspoon cinnamon',
      '½ teaspoon nutmeg or replace with cinnamon',
    ],
    steps: [
      'Butter or spray a 9-inch pie pan with a removable bottom – making sure it is has been adequately sprayed. Set aside',
      'Place flour, salt and sugar in a food processor pulse for a couple of times to mix ingredients.',
      'Throw in butter and pulse until rough dough forms.',
      'Then add egg yolk - pulse until the dough barely comes.',
      'Remove dough place on a work surface - knead just enough to incorporate all the dough. Working the dough as little as possible.',
      'Do not overwork the dough; otherwise it’ll be too tough. When it’s ready, the dough will be barely moistened and come together into a ball.',
      'Lightly press the dough on the prepare pie pan – working from the center up until the bottom and sides are fully covered with pastry – again be very gentle when pressing the dough onto the pie pan.',
      'Place pie pan in the freezer and freeze for at least 30 minutes or more this helps prevent the dough from rising- if you are in a rush brick, then bake with beans to prevent rising.',
      'Preheat oven to 400 degrees F (205 degrees C) and place rack in center of oven',
      'Bake crust for about 20 to 25 minutes or until the crust is dry and golden browned. Set aside',
      'Place saucepan over medium heat, add butter, nutmeg and milk -bring to a boil and remove from the heat.',
      'In another bowl, mix together flour, cornstarch, sugar, vanilla and almond extract- whisk in eggs until smooth. Gently whisk into the saucepan making sure there are no lumps',
      'Now return the pan back on the stove – keep stirring constantly until in starts to bubble.',
      'Cook for about 5-6 minutes. Remove from heat and pour mixture into the baked pastry shell Sprinkle with cinnamon. Chill until ready to be served.',
    ],
    isGlutenFree: false,
    isVegan: false,
    isVegetarian: false,
    isLactoseFree: false,
  ),
  Meal(
    id: 'm3',
    categories: [
      'c2',
      'c3',
    ],
    title: 'Classic Hamburger',
    affordability: Affordability.Pricey,
    complexity: Complexity.Simple,
    imageUrl:
        'https://cdn.pixabay.com/photo/2014/10/23/18/05/burger-500054_1280.jpg',
    duration: 45,
    ingredients: [
      '300g Cattle Hack',
      '1 Tomato',
      '1 Cucumber',
      '1 Onion',
      'Ketchup',
      '2 Burger Buns'
    ],
    steps: [
      'Form 2 patties',
      'Fry the patties for c. 4 minutes on each side',
      'Quickly fry the buns for c. 1 minute on each side',
      'Bruch buns with ketchup',
      'Serve burger with tomato, cucumber and onion'
    ],
    isGlutenFree: false,
    isVegan: false,
    isVegetarian: false,
    isLactoseFree: true,
  ),
  Meal(
    id: 'm4',
    categories: [
      'c4',
    ],
    title: 'Wiener Schnitzel',
    affordability: Affordability.Luxurious,
    complexity: Complexity.Challenging,
    imageUrl:
        'https://cdn.pixabay.com/photo/2018/03/31/19/29/schnitzel-3279045_1280.jpg',
    duration: 60,
    ingredients: [
      '8 Veal Cutlets',
      '4 Eggs',
      '200g Bread Crumbs',
      '100g Flour',
      '300ml Butter',
      '100g Vegetable Oil',
      'Salt',
      'Lemon Slices'
    ],
    steps: [
      'Tenderize the veal to about 2–4mm, and salt on both sides.',
      'On a flat plate, stir the eggs briefly with a fork.',
      'Lightly coat the cutlets in flour then dip into the egg, and finally, coat in breadcrumbs.',
      'Heat the butter and oil in a large pan (allow the fat to get very hot) and fry the schnitzels until golden brown on both sides.',
      'Make sure to toss the pan regularly so that the schnitzels are surrounded by oil and the crumbing becomes ‘fluffy’.',
      'Remove, and drain on kitchen paper. Fry the parsley in the remaining oil and drain.',
      'Place the schnitzels on awarmed plate and serve garnishedwith parsley and slices of lemon.'
    ],
    isGlutenFree: false,
    isVegan: false,
    isVegetarian: false,
    isLactoseFree: false,
  ),
  Meal(
    id: 'm5',
    categories: [
      'c2'
          'c5',
      'c10',
    ],
    title: 'Salad with Smoked Salmon',
    affordability: Affordability.Luxurious,
    complexity: Complexity.Simple,
    imageUrl:
        'https://cdn.pixabay.com/photo/2016/10/25/13/29/smoked-salmon-salad-1768890_1280.jpg',
    duration: 15,
    ingredients: [
      'Arugula',
      'Lamb\'s Lettuce',
      'Parsley',
      'Fennel',
      '200g Smoked Salmon',
      'Mustard',
      'Balsamic Vinegar',
      'Olive Oil',
      'Salt and Pepper'
    ],
    steps: [
      'Wash and cut salad and herbs',
      'Dice the salmon',
      'Process mustard, vinegar and olive oil into a dessing',
      'Prepare the salad',
      'Add salmon cubes and dressing'
    ],
    isGlutenFree: true,
    isVegan: false,
    isVegetarian: true,
    isLactoseFree: true,
  ),
  Meal(
    id: 'm6',
    categories: [
      'c6',
      'c10',
    ],
    title: 'Delicious Orange Mousse',
    affordability: Affordability.Affordable,
    complexity: Complexity.Hard,
    imageUrl:
        'https://cdn.pixabay.com/photo/2017/05/01/05/18/pastry-2274750_1280.jpg',
    duration: 240,
    ingredients: [
      '4 Sheets of Gelatine',
      '150ml Orange Juice',
      '80g Sugar',
      '300g Yoghurt',
      '200g Cream',
      'Orange Peel',
    ],
    steps: [
      'Dissolve gelatine in pot',
      'Add orange juice and sugar',
      'Take pot off the stove',
      'Add 2 tablespoons of yoghurt',
      'Stir gelatin under remaining yoghurt',
      'Cool everything down in the refrigerator',
      'Whip the cream and lift it under die orange mass',
      'Cool down again for at least 4 hours',
      'Serve with orange peel',
    ],
    isGlutenFree: true,
    isVegan: false,
    isVegetarian: true,
    isLactoseFree: false,
  ),
  Meal(
    id: 'm7',
    categories: [
      'c7',
    ],
    title: 'Pancakes',
    affordability: Affordability.Affordable,
    complexity: Complexity.Simple,
    imageUrl:
        'https://cdn.pixabay.com/photo/2018/07/10/21/23/pancake-3529653_1280.jpg',
    duration: 20,
    ingredients: [
      '1 1/2 Cups all-purpose Flour',
      '3 1/2 Teaspoons Baking Powder',
      '1 Teaspoon Salt',
      '1 Tablespoon White Sugar',
      '1 1/4 cups Milk',
      '1 Egg',
      '3 Tablespoons Butter, melted',
    ],
    steps: [
      'In a large bowl, sift together the flour, baking powder, salt and sugar.',
      'Make a well in the center and pour in the milk, egg and melted butter; mix until smooth.',
      'Heat a lightly oiled griddle or frying pan over medium high heat.',
      'Pour or scoop the batter onto the griddle, using approximately 1/4 cup for each pancake. Brown on both sides and serve hot.'
    ],
    isGlutenFree: true,
    isVegan: false,
    isVegetarian: true,
    isLactoseFree: false,
  ),
  Meal(
    id: 'm8',
    categories: [
      'c8',
    ],
    title: 'Creamy Indian Chicken Curry',
    affordability: Affordability.Pricey,
    complexity: Complexity.Challenging,
    imageUrl:
        'https://cdn.pixabay.com/photo/2018/06/18/16/05/indian-food-3482749_1280.jpg',
    duration: 35,
    ingredients: [
      '4 Chicken Breasts',
      '1 Onion',
      '2 Cloves of Garlic',
      '1 Piece of Ginger',
      '4 Tablespoons Almonds',
      '1 Teaspoon Cayenne Pepper',
      '500ml Coconut Milk',
    ],
    steps: [
      'Slice and fry the chicken breast',
      'Process onion, garlic and ginger into paste and sauté everything',
      'Add spices and stir fry',
      'Add chicken breast + 250ml of water and cook everything for 10 minutes',
      'Add coconut milk',
      'Serve with rice'
    ],
    isGlutenFree: true,
    isVegan: false,
    isVegetarian: false,
    isLactoseFree: true,
  ),
  Meal(
    id: 'm9',
    categories: [
      'c9',
    ],
    title: 'Chocolate Souffle',
    affordability: Affordability.Affordable,
    complexity: Complexity.Hard,
    imageUrl:
        'https://cdn.pixabay.com/photo/2014/08/07/21/07/souffle-412785_1280.jpg',
    duration: 45,
    ingredients: [
      '1 Teaspoon melted Butter',
      '2 Tablespoons white Sugar',
      '2 Ounces 70% dark Chocolate, broken into pieces',
      '1 Tablespoon Butter',
      '1 Tablespoon all-purpose Flour',
      '4 1/3 tablespoons cold Milk',
      '1 Pinch Salt',
      '1 Pinch Cayenne Pepper',
      '1 Large Egg Yolk',
      '2 Large Egg Whites',
      '1 Pinch Cream of Tartar',
      '1 Tablespoon white Sugar',
    ],
    steps: [
      'Preheat oven to 190°C. Line a rimmed baking sheet with parchment paper.',
      'Brush bottom and sides of 2 ramekins lightly with 1 teaspoon melted butter; cover bottom and sides right up to the rim.',
      'Add 1 tablespoon white sugar to ramekins. Rotate ramekins until sugar coats all surfaces.',
      'Place chocolate pieces in a metal mixing bowl.',
      'Place bowl over a pan of about 3 cups hot water over low heat.',
      'Melt 1 tablespoon butter in a skillet over medium heat. Sprinkle in flour. Whisk until flour is incorporated into butter and mixture thickens.',
      'Whisk in cold milk until mixture becomes smooth and thickens. Transfer mixture to bowl with melted chocolate.',
      'Add salt and cayenne pepper. Mix together thoroughly. Add egg yolk and mix to combine.',
      'Leave bowl above the hot (not simmering) water to keep chocolate warm while you whip the egg whites.',
      'Place 2 egg whites in a mixing bowl; add cream of tartar. Whisk until mixture begins to thicken and a drizzle from the whisk stays on the surface about 1 second before disappearing into the mix.',
      'Add 1/3 of sugar and whisk in. Whisk in a bit more sugar about 15 seconds.',
      'whisk in the rest of the sugar. Continue whisking until mixture is about as thick as shaving cream and holds soft peaks, 3 to 5 minutes.',
      'Transfer a little less than half of egg whites to chocolate.',
      'Mix until egg whites are thoroughly incorporated into the chocolate.',
      'Add the rest of the egg whites; gently fold into the chocolate with a spatula, lifting from the bottom and folding over.',
      'Stop mixing after the egg white disappears. Divide mixture between 2 prepared ramekins. Place ramekins on prepared baking sheet.',
      'Bake in preheated oven until scuffles are puffed and have risen above the top of the rims, 12 to 15 minutes.',
    ],
    isGlutenFree: true,
    isVegan: false,
    isVegetarian: true,
    isLactoseFree: false,
  ),
  Meal(
    id: 'm10',
    categories: [
      'c2',
      'c5',
      'c10',
    ],
    title: 'Asparagus Salad with Cherry Tomatoes',
    affordability: Affordability.Luxurious,
    complexity: Complexity.Simple,
    imageUrl:
        'https://cdn.pixabay.com/photo/2018/04/09/18/26/asparagus-3304997_1280.jpg',
    duration: 30,
    ingredients: [
      'White and Green Asparagus',
      '30g Pine Nuts',
      '300g Cherry Tomatoes',
      'Salad',
      'Salt, Pepper and Olive Oil'
    ],
    steps: [
      'Wash, peel and cut the asparagus',
      'Cook in salted water',
      'Salt and pepper the asparagus',
      'Roast the pine nuts',
      'Halve the tomatoes',
      'Mix with asparagus, salad and dressing',
      'Serve with Baguette'
    ],
    isGlutenFree: true,
    isVegan: true,
    isVegetarian: true,
    isLactoseFree: true,
  ),
];
